# Generated by Django 3.2.7 on 2021-09-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justice',
            name='name',
        ),
        migrations.AddField(
            model_name='justice',
            name='first_name',
            field=models.CharField(default='J', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justice',
            name='last_name',
            field=models.CharField(default='J', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justice',
            name='middle_initial',
            field=models.CharField(default='J', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='justice',
            name='suffix',
            field=models.CharField(default='J', max_length=5),
            preserve_default=False,
        ),
    ]
