# Generated by Django 3.2.7 on 2021-09-23 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20210923_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justice',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='justice',
            name='suffix',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
