# Generated by Django 3.2.7 on 2021-09-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_auto_20210923_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='justice',
            name='is_sitting_justice',
            field=models.BooleanField(default=False),
        ),
    ]
