# Generated by Django 3.2.7 on 2021-09-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_opinions',
            field=models.ManyToManyField(related_name='case', to='cases.Opinion'),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='opinion_type',
            field=models.CharField(choices=[('M', 'Majority'), ('P', 'Plurality'), ('C', 'Concurring'), ('D', 'Dissenting'), ('CD', 'Concurring in part and dissenting in part')], default='M', max_length=2),
        ),
    ]
