# Generated by Django 3.2.7 on 2021-09-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_auto_20210926_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='syllabus_link',
            new_name='opinion_link',
        ),
        migrations.AlterField(
            model_name='case',
            name='commentary',
            field=models.TextField(blank=True),
        ),
    ]
